### ISSUE TITLE
Feature 

### ISSUE THREAD

**Issue by Poo0oof** [psZachary/lockdown-protocol-external#8]
i was adding Teleport to the code but its not working, and pls add is there any way to change my name and the host name 

else if (selected_tab == 5) {

	calculatedHeight += itemHeight + headerPadding;

	const char* gmae_area_options[] = { "Machine", "Medical", "Camera", "Shipping", "Restaurant", "Lab", "Garden", "Lobby Room" };
	const char* out_of_bound_options[] = {
		"Yellow Apartment",
		"Red Apartment",
		"Shipping Catwalk",
		"Medical Hallway",
		"Restaurant Glass Room",
		"Restaurant Aquarium",
		"Glass Roof Spawn",
		"Lobby Glass Room",
		"Tutorial Room"
	};

	int area_value = 9;
	int area_index = area_value - 1;

	int out_of_bound_value = 10;
	int out_of_bound_index = out_of_bound_value - 1;

	ImGui::Text("Game Area");
	ImGui::SameLine();
	ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x);
	if (ImGui::Combo("##Game Area", &area_index, gmae_area_options, IM_ARRAYSIZE(gmae_area_options))) {
		area_value = area_index + 1;
		// Update net_location.X, net_location.Y, net_location.Z based on selected game area
		const float game_area_coords[][3] = {
			{5159.9999f, 11440.0f, 0.0f}, // Machine
			{6640.1723f, 3640.0f, 0.0f},  // Medical
			{10141.4039f, 11959.9999f, 0.0f}, // Camera
			{3759.9999f, 8559.9999f, 82.5783f}, // Shipping
			{7460.0f, 7940.0f, 0.0f},  // Restaurant
			{8759.9999f, 5544.9045f, 1.1481f}, // Lab
			{11140.0f, 2740.0f, 0.0f},  // Garden
			{11092.6810f, 12646.1616f, 500.0f} // Lobby Room
		};
		auto net_location = local_mec->get_net_location();
		net_location.X = game_area_coords[area_index][0];
		net_location.Y = game_area_coords[area_index][1];
		net_location.Z = game_area_coords[area_index][2];
		local_mec->set_net_location(net_location);
		printf("Net Location after update: %f, %f, %f\n", net_location.X, net_location.Y, net_location.Z);
	}

	ImGui::Text("Out Of Bound");
	ImGui::SameLine();
	ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x);
	if (ImGui::Combo("##OutOfBound", &out_of_bound_index, out_of_bound_options, IM_ARRAYSIZE(out_of_bound_options))) {
		out_of_bound_value = out_of_bound_index + 1;
		// Update net_location.X, net_location.Y, net_location.Z based on selected out of bound location
		const float out_of_bound_coords[][3] = {
			{10686.7087f, 6287.1945f, 500.0f}, // Yellow Apartment
			{8496.1249f, 10656.7508f, 1000.0f}, // Red Apartment
			{5105.8489f, 8559.9999f, 500.0f}, // Shipping Catwalk
			{3706.2617f, 3631.1171f, 0.0f}, // Medical Hallway
			{5940.0f, 7940.0f, 0.0f}, // Restaurant Glass Room
			{5802.8089f, 7024.6166f, 125.1444f}, // Restaurant Aquarium
			{10596.4800f, 8701.4533f, 1500.0f}, // Glass Roof Spawn
			{10128.0709f, 12433.8404f, 500.0f}, // Lobby Glass Room
			{8560.6636f, 20154.4441f, 500.0f} // Tutorial Room
		};
		auto net_location = local_mec->get_net_location();

		net_location.X = out_of_bound_coords[out_of_bound_index][0];
		net_location.Y = out_of_bound_coords[out_of_bound_index][1];
		net_location.Z = out_of_bound_coords[out_of_bound_index][2];
		local_mec->set_net_location(net_location);
		printf("Net Location after update: %f, %f, %f\n", net_location.X, net_location.Y, net_location.Z);
		auto net_location2 = local_mec->get_net_location();
		printf("Net Location after update: %f, %f, %f\n", net_location2.X, net_location2.Y, net_location2.Z);

	}
	calculatedHeight += itemHeight;

}

**Comment by OniSensei** [comment]
Teleport in external is not possible.

**Comment by Poo0oof** [comment]
what about changing the name or host name? and i saw somting like people with red head and white body is that possible ?

**Comment by OniSensei** [comment]
Unfortunately these are both FStrings which do not convert properly for editing. If you would like to help in coding the proper structure it is located in game_structures.hpp:
```
// fix later, fuk u bditt
class fstring : public t_array<wchar_t> {
public:
	std::string read_string() {
		if (count <= 0 || count > 500)
		{
			return std::string();
		}

		auto test = mem::rpm<wchar_holder>(_data);
		char ch[260];
		char DefChar = ' ';
		WideCharToMultiByte(CP_ACP, 0, test.data, -1, ch, 260, &DefChar, NULL);
		std::string ss(ch);
		return ss;
	}
};
```

**Comment by Poo0oof** [comment]
tnx let me check
